captureDirectory: capturing
completeDirectory: captured
modelScanInterval: 300
autoConvertType: mp4
autoDelete: false
dateFormat: YYYYMMDD-HHmmss
debug: true
modelcolor: magenta
timecolor: grey
sitecolor: green
debugcolor: yellow
errorcolor: red
includeSiteInFile: true
enableMFC: true
enableCB: true
enableIF: true
mfcmodels:
  - 3623822
  - 12513225
  - 15761593
  - 4585086
cbmodels:
  - aynmarie
  - theemilygrey
  - katyandmax
