captureDirectory: 'capturing'
completeDirectory: 'captured'
modelScanInterval: 300
autoConvertType: mp4  # also mkv or none (leaves as ts)
dateFormat: YYYYMMDD-HHmmss
debug: true
modelcolor: magenta
timecolor: grey
sitecolor: green
debugcolor: yellow
errorcolor: red
includeSiteInFile: true
mfcmodels:
  - 5479250  # ItalianBoobs
  - 20249367 # KatyaFods
  - 17030607 # oKRYSTALo
cbmodels:
  - sexxylorry
  - sophieandkaiden
includeMfcModels:
  - MODELNAMETOSTARTCAPTURING
excludeMfcModels:
  - MODELNAMETOSTOPCAPTURING
includeCbModels:
  - MODELNAMETOSTARTCAPTURING
excludeMfcModels:
  - MODELNAMETOSTOPCAPTURING
