captureDirectory: capturing
completeDirectory: captured
modelSubdir: true
modelScanInterval: 100
autoConvertType: mp4
keepTsFile: false
minByteSize: 0
maxByteSize: 0
notifications: true
dateFormat: YYYYMMDD_HHmmss
debug: false
modelcolor: magenta
timecolor: grey
sitecolor: green
debugcolor: yellow
errorcolor: red
includeSiteInFile: false
includeSiteInDir: false
enableMFC: false
enableCB: true
mfcmodels: null
cbmodels:
  - test
