captureDirectory: capturing
completeDirectory: captured
modelScanInterval: 350
autoConvertType: mp4 # also mkv or none to leave as ts
autoDelete: false # warning: setting to true will delete captures
dateFormat: YYYYMMDD-HHmmss
debug: true
modelcolor: magenta
timecolor: grey
sitecolor: green
debugcolor: yellow
errorcolor: red
includeSiteInFile: true
enableMFC: true
enableCB: true
mfcmodels:
  - 3623822
  - 12513225
cbmodels:
  - aynmarie
  - theemilygrey
