captureDirectory: 'N:\Chaturbate\capturing'
completeDirectory: 'N:\Chaturbate\captured'
modelSubdir: true
modelScanInterval: 100
autoConvertType: mp4
keepTsFile: false
minByteSize: 0
maxByteSize: 0
notifications: true
dateFormat: YYYYMMDD_HHmmss
debug: false
modelcolor: magenta
timecolor: grey
sitecolor: green
debugcolor: yellow
errorcolor: red
includeSiteInFile: false
includeSiteInDir: false
enableMFC: false
enableCB: true
mfcmodels: null
cbmodels:
  - west_coast_dude
  - teron_james
  - kingofonehorsetown
  - theguy856
  - blackxjack98
  - highandhairy
  - dehazee
  - klim200
  - hornygam3r
  - twinkup4play
  - phitt
  - darek_horny
  - mewtwo__
  - frenchyooungboy
  - badboyx1
  - txsymbolic
  - mismatched
  - bigbananaforsure
  - suziemorgan
  - calvinhuge1
  - aalex98765
